site_name: Crane Cloud
nav:
  - Quickstart:
      - Quickstart: quickstart/quickstart.md
  - Authentication:
      - Registration: authentication/registration.md
      - Account Verification: authentication/accountVerification.md
      - Login: authentication/login.md
      - User Dashboard: authentication/userDashboard.md
      - Forgot Password: authentication/forgotPassword.md
  - Projects:
      - Projects: projects/projects.md
  - Applications:
     - Application Containerization: applications/appContainerization.md
     - Application Deployment: applications/deployApp.md
     - Deploy Application without Database Support: applications/deployWithoutDB.md
     - Deploy an app Image from Docker with Database Support: applications/dockerWithDB.md
     - Deploy an app Image from GCR with Database Support: applications/gcrWithDB.md
     - Delete deployed application: applications/deleteApp.md
  - Databases:
      - Database Support: databases/info.md
theme:
  name: material
  palette:
    scheme: slate
    primary: light blue
    accent: blue