site_name: Crane Cloud
nav:
  - Quickstart:
      - Quickstart: quickstart/quickstart.md
  - Authentication:
      - Registration: authentication/registration.md
      - Account Verification: authentication/accountVerification.md
      - Login: authentication/login.md
      - User Dashboard: authentication/userDashboard.md
      - Forgot Password: authentication/forgotPassword.md
  - Projects:
      - Projects: projects/projects.md
  - Applications:
      - Application Containerization: applications/appContainerization.md
      - Application Deployment: applications/deployApp.md
      - Deploy stand-alone Application: applications/deployWithoutDB.md
      - Deploy an app Image from Docker: applications/dockerWithDB.md
      - Deploy an app Image from GCR: applications/gcrWithDB.md
      - Update an app deployment: applications/updateApp.md
      - Delete deployed application: applications/deleteApp.md
      - Add Custom Domain: applications/customDomain.md
  - Deployment Guides:
      - Deploy a React App: guides/deployReactApp.md
      - Deploy a Node App: guides/deployNodeApp.md
      - Deploy a Flask App: guides/deployFlaskApp.md
  - Databases:
      - Databases: databases/database.md
  - Monitoring:
      - Project Monitoring: monitoring/projects.md
      - Application Monitoring: monitoring/appMetrics.md
theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo.svg
  font:
    text: Nunito
    code: Nunito
  palette:
    scheme: slate
    primary: light blue
    accent: blue
