site_name: Crane Cloud
nav:
  - Authentication:
      - Registration: authentication/registration.md
      - Account Verification: authentication/accountVerification.md
      - Login: authentication/login.md
      - User Dashboard: authentication/userDashboard.md
      - Forgot Password: authentication/forgotPassword.md
  - Projects:
      - Projects: projects/projects.md
      - Project Collaboration: projects/projectCollaboration.md
  - Applications:
      - Deploy stand-alone Application: applications/deployWithoutDB.md
      - Update deployed application: applications/updateApp.md
      - Delete deployed application: applications/deleteApp.md
      - Add Custom Domain: applications/customDomain.md
      - Deploy an app using the MIRA service: applications/deployWithMira.md
      - Deploy microservices: applications/microservices.md
      - Implement CI/CD with Docker WebHook: applications/webHook.md
  - Deployment Guides:
      - Deploy an HTML App: guides/deployHtmlApp.md
      - Deploy a ReactJs App: guides/deployReactApp.md
      - Deploy a NodeJs App: guides/deployNodeApp.md
      - Deploy a Flask App: guides/deployFlaskApp.md
      - Deploy a Laravel App: guides/deployLaravelApp.md
  - Databases:
      - Databases: databases/database.md
  - Crane Cloud CLI Client:
      - Using python pip: cli/pip_cli.md
  - Monitoring:
      - Project monitoring: monitoring/projects.md
      - Application monitoring: monitoring/appMetrics.md
  - Learning Tools:
      - Self Managed Gitlab: learning/gitlab.md
theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo.svg
  font:
    text: Plus Jakarta Sans
    code: Source Code Pro
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: blues
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - extra.css