site_name: Crane Cloud
nav:
  - quickstart:
      - quickstart: quickstart/quickstart.md
  - Projects:
      - projects: projects/projects.md
  - Applications: apps.md
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue