site_name: Crane Cloud
nav:
  - Home: index.md
  - User accounts:
      - Create an account: user-accounts/registration.md
      - Account verification: user-accounts/account-verification.md
      - Access your account: user-accounts/login.md
      - Forgot password: user-accounts/forgot-password.md
  - Projects:
      - Projects: projects/index.md
      - Project collaboration: projects/project-collaboration.md
  - Applications:
      - Deploy single application: applications/deploy-singleApp.md
      - Deploy applications using MIRA: applications/deploy-usingMira.md
      - Deploy microservices: applications/deploy-microservices.md
      - Application management: applications/management.md
  - Deployment Guides:
      - Deploy an HTML App: guides/deployHtmlApp.md
      - Deploy a ReactJs App: guides/deployReactApp.md
      - Deploy a NodeJs App: guides/deployNodeApp.md
      - Deploy a Flask App: guides/deployFlaskApp.md
      - Deploy a Laravel App: guides/deployLaravelApp.md
  - Databases:
      - Databases: databases/index.md
  - Crane Cloud CLI Client:
      - Using python pip: command-line-interface/using-python-pip.md
  - Monitoring:
      - Project monitoring: monitoring/projects.md
      - Application monitoring: monitoring/applications.md
  - Learning Tools:
      - Self managed Gitlab: learning/gitlab.md
theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo.svg
  font:
    text: Plus Jakarta Sans
    code: Source Code Pro
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: blues
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - extra.css