site_name: Crane Cloud
nav:
  - quickstart:
      - quickstart: quickstart/quickstart.md
  - Authentication:
      - Registration: authentication/registration.md
      - Account Verification: authentication/accountVerification.md
      - Login: authentication/login.md
      - User Dashboard: authentication/userDashboard.md
      - Forgot Password: authentication/forgotPassword.md
  - Projects:
      - projects: projects/projects.md
  - Applications: apps.md
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue