site_name: Crane Cloud
nav:
  - quickstart:
      - quickstart: quickstart/quickstart.md
  - Projects: project.md
  - Applications:
     - Application Containerization: applications/appContainerization.md
     - Application Creation/Deployment: applications/deployApp.md
     - Deploy Application without Database Support: applications/deployWithoutDB.md
     - Deploy an app Image from Docker with Database Support: applications/dockerWithDB.md
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue